// Code generated by baton-sdk. DO NOT EDIT!!!
package config

import "reflect" 

type Aws struct {
	ExternalId string `mapstructure:"external-id"`
	GlobalAccessKeyId string `mapstructure:"global-access-key-id"`
	GlobalAwsOrgsEnabled bool `mapstructure:"global-aws-orgs-enabled"`
	GlobalAwsSsoEnabled bool `mapstructure:"global-aws-sso-enabled"`
	GlobalAwsSsoRegion string `mapstructure:"global-aws-sso-region"`
	GlobalBindingExternalId string `mapstructure:"global-binding-external-id"`
	GlobalRegion string `mapstructure:"global-region"`
	GlobalRoleArn string `mapstructure:"global-role-arn"`
	GlobalSecretAccessKey string `mapstructure:"global-secret-access-key"`
	RoleArn string `mapstructure:"role-arn"`
	ScimEnabled bool `mapstructure:"scim-enabled"`
	ScimEndpoint string `mapstructure:"scim-endpoint"`
	ScimToken string `mapstructure:"scim-token"`
	UseAssume bool `mapstructure:"use-assume"`
	SyncSecrets bool `mapstructure:"sync-secrets"`
	IamAssumeRoleName string `mapstructure:"iam-assume-role-name"`
	SyncSsoUserLastLogin bool `mapstructure:"sync-sso-user-last-login"`
}

func (c *Aws) findFieldByTag(tagValue string) (any, bool) {
	v := reflect.ValueOf(c).Elem() // Dereference pointer to struct
	t := v.Type()

	for i := 0; i < t.NumField(); i++ {
		field := t.Field(i)
		tag := field.Tag.Get("mapstructure")

		if tag == tagValue {
			return v.Field(i).Interface(), true
		}
	}
	return nil, false
}

func (c *Aws) GetStringSlice(fieldName string) []string {
	v, ok := c.findFieldByTag(fieldName)
	if !ok {
		return []string{}
	}
	t, ok := v.([]string)
	if !ok {
		panic("wrong type")
	}
	return t
}

func (c *Aws) GetString(fieldName string) string {
	v, ok := c.findFieldByTag(fieldName)
	if !ok {
		return ""
	}
	if t, ok := v.(string); ok {
		return t
	}
	if t, ok := v.([]byte); ok {
		return string(t)
	}
	panic("wrong type")
}

func (c *Aws) GetInt(fieldName string) int {
	v, ok := c.findFieldByTag(fieldName)
	if !ok {
		return 0
	}
	t, ok := v.(int)
	if !ok {
		panic("wrong type")
	}
	return t
}

func (c *Aws) GetBool(fieldName string) bool {
	v, ok := c.findFieldByTag(fieldName)
	if !ok {
		return false
	}
	t, ok := v.(bool)
	if !ok {
		panic("wrong type")
	}
	return t
}

func (c *Aws) GetStringMap(fieldName string) map[string]any {
	v, ok := c.findFieldByTag(fieldName)
	if !ok {
		return map[string]any{}
	}
	t, ok := v.(map[string]any)
	if !ok {
		panic("wrong type")
	}
	return t
}
